src/test/java/com/example/fanmix/api/domain/member/MemberServiceTest.java

main브런치는 바로 올라가는것 같고
develop브런치는 pr로 올라가는 것 같음

feat : 필요없는 테스트 제거

---

build.gradle
src/test/java/com/fanmix/api/common/GoogleLoginServiceTest.java

fix : 하드코딩한 테스트는 @Disabled 처리

---

build.gradle

테스트에 롬복 의존성 추가
이제 메인에서 테스트 통과 될것같습니다.

fix : 테스트에서도 롬복 쓰기위해 의존성 추가

---

src/test/java/com/fanmix/api/common/GoogleLoginServiceTest.java

하드코딩 테스트제거
깃헙에서는 @Disabled 붙여도 검사를 함.

fix : 하드코딩 테스트 제거

---

src/test/java/com/fanmix/api/domain/member/MemberControllerTest.java
src/test/java/com/fanmix/api/domain/member/MemberServiceTest.java

fix : api구현된 테스트들 모두 제거

---

src/main/java/com/fanmix/api/domain/member/exception/MemberErrorCode.java
src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java
src/main/resources/templates/auth/redirect.html

소셜로그인 배포서버에서 에러나서 확인하는 예외처리 추가

fix : 소셜로그인 배포서버에서 에러나서 확인하는 예외처리 추가

---

src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java

fix : 로컬과 배포 다르게 적용된것 체크중

---

src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java

Security 설정에 클라이언트 배포서버 redirect 쪽도 허용에 넣어봄

fix : Security 설정에 클라이언트 배포서버 redirect 쪽도 허용에 넣어봄

---

src/main/java/com/fanmix/api/domain/member/exception/MemberErrorCode.java
src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java

- Change 1
- Description
- Change 2
- Change 3

fix : 이거안되면 application-prod의 redirect-uri문제

---

src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java

fix : info로 파라미터 파악

---

src/main/java/com/fanmix/api/common/conf/SecurityConfig.java

- Change 1
- Description
- Change 2
- Change 3

feat : 스프링 시큐리티에서 cors정책

---

src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java

- Change 1
- Description
- Change 2
- Change 3

fix : 클라이언트에서 리프레쉬토큰이 비어서 왔음

---

src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/domain/common/UserMode.java
src/main/java/com/fanmix/api/domain/influencer/entity/SocialMedia.java
src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
src/main/java/com/fanmix/api/domain/member/dto/MemberResponseDto.java
src/main/java/com/fanmix/api/domain/member/entity/Member.java
src/main/java/com/fanmix/api/domain/member/repository/MemberRepository.java
src/main/java/com/fanmix/api/domain/member/service/GoogleLoginService.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
src/main/java/com/fanmix/api/domain/review/service/ReviewService.java

2. SecurityConfig에 "/api/public"으로 시작되는건 권한 체크 해제
3. influencerService의 BigDecimal 예외는 커밋하지 않음
4. /api/public/members/{memberId}/activity/reviews  조회시 순환참조발생
최신화로 메인에 병합

feat : 1. Member의 SocialId를 UserMode로 변경.  Enum추가

---

src/main/java/com/fanmix/api/domain/fan/entity/Fan.java
src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
src/main/java/com/fanmix/api/domain/influencer/entity/InfluencerRatingCache.java
src/main/java/com/fanmix/api/domain/influencer/entity/SocialMedia.java
src/main/java/com/fanmix/api/domain/influencer/entity/tag/InfluencerTag.java
src/main/java/com/fanmix/api/domain/review/entity/Review.java
src/main/java/com/fanmix/api/domain/review/entity/ReviewComment.java
src/main/java/com/fanmix/api/domain/review/entity/ReviewLikeDislike.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java

Entity 를 ERD 에 맞춰 리팩토링한거 배포 서버에 적용 위한 PR

Entity Erd 에 맞춰 리팩토링

---

src/main/java/com/fanmix/api/domain/fan/entity/FanRepository.java

:bug: fix: fanRepository 중복 삭제

---

src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
src/main/java/com/fanmix/api/domain/member/dto/LatestReviewResponseDto.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java
src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
src/main/java/com/fanmix/api/domain/review/entity/Review.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepository.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewQuerydslRepositoryImpl.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java
src/main/java/com/fanmix/api/domain/review/service/ReviewService.java

✨ feat:#16 리뷰 관련 모든 api 구현

---

src/main/java/com/fanmix/api/common/redis/constants/InfluencerRedisConstants.java
src/main/java/com/fanmix/api/domain/influencer/controller/InfluencerController.java
src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
src/main/java/com/fanmix/api/domain/influencer/repository/InfluencerRepository.java
src/main/java/com/fanmix/api/domain/influencer/service/InfluencerScheduledService.java
src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java

✨ feat:#16 관련 모든 api 구현

---

src/main/java/com/fanmix/api/common/conf/CustomAccessDeniedHandler.java
src/main/java/com/fanmix/api/common/conf/CustomAuthenticationEntryPoint.java
src/main/java/com/fanmix/api/common/conf/JwtExpiredEntryPoint.java
src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/common/security/filter/JwtTokenFilter.java
src/main/java/com/fanmix/api/common/security/util/JwtTokenUtil.java
src/main/java/com/fanmix/api/domain/comment/repository/CommentRepository.java
src/main/java/com/fanmix/api/domain/fan/entity/Fan.java
src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
src/main/java/com/fanmix/api/domain/member/dto/MemberActivityCommentDto.java
src/main/java/com/fanmix/api/domain/member/dto/MemberActivityDto.java
src/main/java/com/fanmix/api/domain/member/dto/MemberActivityPostDto.java
src/main/java/com/fanmix/api/domain/member/dto/MemberActivityReviewDto.java
src/main/java/com/fanmix/api/domain/member/exception/MemberErrorCode.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java
src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java

develop 에서 테스트 및 구현완료된 기능들 배포 위한 Main 으로 merge

배포 위한 Develop -> Main PR

---

src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
src/main/java/com/fanmix/api/domain/influencer/entity/Influencer.java
src/main/java/com/fanmix/api/domain/member/controller/MemberController.java
src/main/java/com/fanmix/api/domain/member/dto/MyFollowResponseDto.java
src/main/java/com/fanmix/api/domain/member/enums/FollowSort.java
src/main/java/com/fanmix/api/domain/member/exception/MemberErrorCode.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java

팬채널 아이디 갖고오는거 하면 완료
- Change 1
- Description
- Change 2
- Change 3

feat : 내가 팔로우하고있는 인플루언서 목록, 원픽 인플루언서 조회, 원픽인플루언서 지정/해제 개발 완료

---

src/main/java/com/fanmix/api/domain/community/repository/CommunityRepository.java
src/main/java/com/fanmix/api/domain/influencer/dto/response/InfluencerResponseDto.java
src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java

#16 api 에서 추가된 정보 추가
단순 정보 추가 리팩토링이라 develop 에서 작업 후 main 에 머지

♻️ refactor:#16 api 에서 추가된 정보 추가

---

src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java

- Change 1
- Description
- Change 2
- Change 3

fix : 인플루언서 상세조회에 communityId가 없더라도 예외가 아니라 해당속성만 null로 들어가게 수정

---

src/main/java/com/fanmix/api/domain/review/controller/ReviewController.java
src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
src/main/java/com/fanmix/api/domain/review/service/ReviewService.java

#48 이슈 관련
Review 도메인 task 완료
단순 dto 추가하고 반영하는거라 바로 develop -> main

♻️ refactor:#48 에서 Review 도메인 task 완료

---

src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
src/main/java/com/fanmix/api/domain/comment/dto/AddCommentRequest.java
src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
src/main/java/com/fanmix/api/domain/comment/entity/Comment.java
src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
src/main/java/com/fanmix/api/domain/community/dto/CommunityResponse.java
src/main/java/com/fanmix/api/domain/community/service/CommunityService.java
src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java
src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
src/main/java/com/fanmix/api/domain/post/controller/PostController.java
src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java
src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
src/main/java/com/fanmix/api/domain/post/service/PostService.java

커뮤니티, 팬채널 추가, 생성 api Reponse 수정
Feat/community -> Develop PR
- Change 1
- 커뮤니티, 팬채널 등록/수정 reponse 수정
- Change 2
-  커뮤니티, 팬채널 게시물 등록/수정 reponse 수정
- Change 3
-  커뮤니티, 팬채널 댓글 등록/수정 reponse 수정

♻️ refactor: 커뮤니티, 팬채널 관련 등록/수정 api Reponse 수정

---

src/main/java/com/fanmix/api/domain/review/dto/response/ReviewResponseDto.java
src/main/java/com/fanmix/api/domain/review/service/ReviewService.java

🚑 !HOTFIX:#48 관련해서 Entity -> dto 변환간 실수 수정
- Change 1
- b5aee3c6507fa7b26027d52fd67cd19edbf7316f: Entity -> dto 변환간 boolean 반대로 하는 실수 수정, 그리고 해당 비슷한 실수 반복 않기 위한 로직 변경
급하게 하다보니 실수를 했습니다 죄송합니다.

🚑 !HOTFIX:#48 관련해서 Entity -> dto 변환간 실수 수정

---

src/main/java/com/fanmix/api/domain/review/repository/ReviewLikeDislikeRepository.java
src/main/java/com/fanmix/api/domain/review/service/ReviewService.java

♻️ refactor: 인기글 Top5 조회시 Response 형식 수정

---

src/main/java/com/fanmix/api/domain/member/service/MemberService.java
src/main/java/com/fanmix/api/domain/review/repository/ReviewRepository.java

- Change 1
- Description
- Change 2
- Change 3

fix : 팔로우하고있는 인플루언서의 나의 평균점수 계산할때 지운 리뷰는 제거하도록 수정

---

src/main/java/com/fanmix/api/domain/member/controller/MemberController.java

- Change 1
- Description
- Change 2
- Change 3

fix : boolean  아니고 Boolean이여서 1넘기니까 제대로안되던것 수정

---

src/main/java/com/fanmix/api/domain/fan/repository/FanRepository.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java

- Change 1
- Description
- Change 2
- Change 3

fix : 원픽일플루언서 지정때 기존에 지정됐던 원픽인플루언서 해제하는것 추가

---

src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java

- Change 1
- Description
- Change 2
- Change 3

fix : 원픽인플루언서 조회. 로그인안해도, 타인것도 조회가능하도록 변경

---

src/main/java/com/fanmix/api/domain/community/controller/FanChannelController.java
src/main/java/com/fanmix/api/domain/community/dto/FanChannelResponse.java
src/main/java/com/fanmix/api/domain/community/service/FanChannelService.java

…false로설정
인증된 인플루언서만 팬채널로써 조회 가능하도록 수정, 비로그인 상태일 때는 팔로잉 여부 false로 변경
- Change 1
- AuthenticationStatus.APPROVED 일때만 조회
- Change 2
- 비로그인시 isFollowing false로 설정
- Change 3

:recycle: refactor: 인증된 인플루언서만 팬채널로써 조회 가능하도록 수정, 비로그인 상태일 때는 팔로잉 여부 false로 변경

---

src/main/java/com/fanmix/api/domain/influencer/service/InfluencerService.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java

♻️ refactor: #61 관련해서 로직 수정, response 수정

---

src/main/java/com/fanmix/api/domain/member/dto/MemberActivityReviewDto.java
src/main/java/com/fanmix/api/domain/member/service/MemberService.java

1. contentRating 에서 contentsRating 으로 s추가
2. 좋아요, 싫어요, 댓글수 추가

fix : 활동이력(한줄리뷰)

---

src/main/java/com/fanmix/api/domain/member/service/MemberService.java

3활동이력3개 로그인 안돼있어서 호출, 팬(팔로우) 상태 아니면 예외가 아니라 빈데이터 반환

fix : 3활동이력3개 로그인 안돼있어서 호출, 팬(팔로우) 상태 아니면 예외가 아니라 빈데이터 반환

---

src/main/java/com/fanmix/api/common/conf/CustomAuthenticationEntryPoint.java
src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/common/security/filter/JwtTokenFilter.java

- Change 1
- Description
- Change 2
- Change 3

fix : 멤버 프로필 api는 로그인 관련없이 허용되도록 수정

---

src/main/java/com/fanmix/api/domain/community/controller/CommunityController.java
src/main/java/com/fanmix/api/domain/community/dto/CommunityNewPostResponse.java
src/main/java/com/fanmix/api/domain/community/service/CommunityService.java

커뮤니티에 오늘 안에 새 글이 올라왔는지 여부와 전체 커뮤니티 카테고리 리턴
- Change 1
- post의 localDate로 오늘 올라온 글인지 필터

:sparkles: feat: 커뮤니티에 오늘 안에 새 글이 올라왔는지 여부

---

src/main/java/com/fanmix/api/common/conf/CustomAuthenticationEntryPoint.java
src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/common/security/filter/JwtTokenFilter.java

✨ Develop -> Main Merge PR

---

src/main/java/com/fanmix/api/domain/comment/controller/CommentController.java
src/main/java/com/fanmix/api/domain/comment/controller/FanChannelCommentController.java
src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
src/main/java/com/fanmix/api/domain/comment/service/CommentService.java
src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java
src/main/java/com/fanmix/api/domain/post/controller/FanChannelPostController.java
src/main/java/com/fanmix/api/domain/post/controller/PostController.java
src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
src/main/java/com/fanmix/api/domain/post/repository/PostRepository.java
src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
src/main/java/com/fanmix/api/domain/post/service/PostService.java

커뮤니티, 팬채널 글, 댓글 목록 / 글 상세 조회시 내가 작성한 글/댓글인지 여부 넘김
- Change 1
- 커뮤니티, 팬채널 글 목록 조회시 내가 작성한 글인지 여부
- Change 2
- 커뮤니티, 팬채널 댓글 목록 조회시 내가 작성한 글인지 여부
- Change 3
- 커뮤니티, 팬채널 글 상세 조회시 내가 작성한 글인지 여부

✨ feat: 커뮤니티, 팬채널 글, 댓글 목록 / 글 상세 조회시 내가 작성한 글/댓글인지 여부 넘기기

---

src/main/java/com/fanmix/api/domain/comment/service/FanChannelCommentService.java

:bug: fix: 팬채널 댓글 목록 조회시 멤버 권한 조건 수정

---

src/main/java/com/fanmix/api/common/conf/CustomAuthenticationEntryPoint.java
src/main/java/com/fanmix/api/common/conf/SecurityConfig.java
src/main/java/com/fanmix/api/common/exception/CommonErrorCode.java
src/main/java/com/fanmix/api/common/exception/CommonExceptionHandler.java
src/main/java/com/fanmix/api/common/security/filter/JwtTokenFilter.java

Develop -> Main Merge PR

---

src/main/java/com/fanmix/api/domain/comment/dto/CommentDetailResponse.java
src/main/java/com/fanmix/api/domain/comment/dto/CommentResponse.java
src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
src/main/java/com/fanmix/api/domain/post/service/PostService.java

커뮤니티, 팬채널 삭제된 게시물 제외 빠진 부분 추가, 커뮤니티, 팬채널 댓글 삭제 여부 돌려주기

🐛 fix: 커뮤니티, 팬채널 삭제된 게시물 제외 빠진 부분 추가

---

src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
src/main/java/com/fanmix/api/domain/post/repository/PostLikeDisLikeRepository.java
src/main/java/com/fanmix/api/domain/post/service/FanChannelPostService.java
src/main/java/com/fanmix/api/domain/post/service/PostService.java

커뮤니티, 팬채널 글 상세 조회시 내가 추천/비추천 했는지 여부
- Change 1
-  커뮤니티 글 상세 조회시 내가 추천/비추천 했는지 여부
- Change 2
-  팬채널 글 상세 조회시 내가 추천/비추천 했는지 여부
- Change 3

✨ feat: 커뮤니티, 팬채널 글 상세 조회시 내가 추천/비추천 했는지 여부

---

src/main/java/com/fanmix/api/domain/post/dto/FanChannelPostResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostDetailResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostListResponse.java
src/main/java/com/fanmix/api/domain/post/dto/PostResponse.java

커뮤니티, 팬채널 글 상세/목록 조회 Response 형식에 memberId 추가
- Change 1
-  커뮤니티 글 상세/목록 조회 Response 형식에 memberId 추가
- Change 2
-  팬채널 글 상세/목록 조회 Response 형식에 memberId 추가
- Change 3

:sparkles: feat: 커뮤니티, 팬채널 글 상세/목록 조회 Response 형식에 memberId 추가
